name: pnlpipe

dependencies:
  - python=2.7
  - plumbum
  - future
  - numpy
  - pandas
  - vtk
  - nibabel
  - pyyaml
  - pip:
     - git+https://github.com/dstrohl/Python_log_indenter.git
     - git+https://github.com/npcole/npyscreen.git
