name: pnlpipe3

dependencies:
  - python=3.6
  - plumbum
  - future
  - numpy
  - pandas
  - vtk
  - cmake
  - nibabel
  - pyyaml
  - psutil
  - csvkit
  - cython
  - joblib
  - matplotlib
  - pip:
     - git+https://github.com/dstrohl/Python_log_indenter.git
