name: pnlpipe

dependencies:
  - python=2.7
  - plumbum
  - future
  - numpy
  - pandas
  - cmake
  - psutil
  - vtk
  - nibabel
  - pyyaml
  - csvkit
  - cython
  - joblib
  - matplotlib
  - pip:
     - git+https://github.com/dstrohl/Python_log_indenter.git
